
package tn.enicarthage.proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueWS", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWS {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convert", targetNamespace = "http://service/", className = "tn.enicarthage.proxy.Convert")
    @ResponseWrapper(localName = "convertResponse", targetNamespace = "http://service/", className = "tn.enicarthage.proxy.ConvertResponse")
    @Action(input = "http://service/BanqueWS/convertRequest", output = "http://service/BanqueWS/convertResponse")
    public double convert(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param id
     * @return
     *     returns tn.enicarthage.proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://service/", className = "tn.enicarthage.proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://service/", className = "tn.enicarthage.proxy.GetCompteResponse")
    @Action(input = "http://service/BanqueWS/getCompteRequest", output = "http://service/BanqueWS/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @return
     *     returns java.util.List<tn.enicarthage.proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listComptes", targetNamespace = "http://service/", className = "tn.enicarthage.proxy.ListComptes")
    @ResponseWrapper(localName = "listComptesResponse", targetNamespace = "http://service/", className = "tn.enicarthage.proxy.ListComptesResponse")
    @Action(input = "http://service/BanqueWS/listComptesRequest", output = "http://service/BanqueWS/listComptesResponse")
    public List<Compte> listComptes();

}
